openapi: 3.0.0
info:
  title: Example API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
- url: localhost:3000
  description: This project is supposed to run locally only
paths:
  /signup:
    post:
      x-eov-operation-id: signup
      x-eov-operation-handler: /auth/index.ts
      summary: Signup
      description: Signup via magic link
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: ok
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /login:
    post:
      x-eov-operation-id: login
      x-eov-operation-handler: /auth/index.ts
      summary: Login
      description: Login via magic link
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: ok
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /hello:
    get:
      x-eov-operation-id: GET
      x-eov-operation-handler: /hello/hello-controller.ts
      summary: Hello
      description: Returns an Hello Object
      security:
      - BearerAuth: []
      parameters:
      - in: query
        name: size
        required: true
        schema:
          type: integer
          minimum: 1
        description: The size of the hello to generate expressed
      responses:
        '200':    # status code
          description: A hello
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Hello'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Hello:
      type: object
      description: A hello object
      properties:
        name:
          type: string
        size:
          type: integer
          minimum: 1
